# .github/workflows/test.yml
name: Test
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Your original steps
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install
        run: npm install
      - name: Prepeare test
        run: npm run test:migrate
      - name: Test and Coverage
        run: npm run test # or npm run coverage
      - name: Rename coverage summary
        run: mv coverage/coverage-final.json coverage/coverage-summary.json

      - name: Update Coverage Badge
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: we-cli/coverage-badge-action@main
