# .github/workflows/test.yml
name: Test
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Your original steps
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install
        run: npm install
      - name: Prepare test
        run: npm run test:migrate
      - name: Test and Coverage
        run: npm run test
